fun main() {
    println("=== GESTOR DE INFORMACIÓN PERSONAL EN KOTLIN ===")
    
    // Usuario 1
    println("Registro de Usuario 1")
    print("Nombre completo: ")
    val nombre1 = readln()
    print("Edad: ")
    val edad1 = readln().toInt()
    print("Altura (en metros): ")
    val altura1 = readln().toDouble()
    print("Peso (en kilogramos): ")
    val peso1 = readln().toDouble()
    print("Email: ")
    val email1 = readln()
    print("Ciudad de residencia: ")
    val ciudad1 = readln()
    
    val imc1 = peso1 / (altura1 * altura1)
    
    println("\n=== INFORMACIÓN DE USUARIO 1 ===")
    println("Nombre: $nombre1")
    println("Edad: $edad1 años")
    println("Altura: $altura1 m")
    println("Peso: $peso1 kg")
    println("IMC: $imc1")
    println("Email: $email1")
    println("Ciudad: $ciudad1")
    
    // Usuario 2
    println("\nRegistro de Usuario 2")
    print("Nombre completo: ")
    val nombre2 = readln()
    print("Edad: ")
    val edad2 = readln().toInt()
    print("Altura (en metros): ")
    val altura2 = readln().toDouble()
    print("Peso (en kilogramos): ")
    val peso2 = readln().toDouble()
    print("Email: ")
    val email2 = readln()
    print("Ciudad de residencia: ")
    val ciudad2 = readln()
    
    val imc2 = peso2 / (altura2 * altura2)
    
    println("\n=== INFORMACIÓN DE USUARIO 2 ===")
    println("Nombre: $nombre2")
    println("Edad: $edad2 años")
    println("Altura: $altura2 m")
    println("Peso: $peso2 kg")
    println("IMC: $imc2")
    println("Email: $email2")
    println("Ciudad: $ciudad2")
    
    // Usuario 3
    println("\nRegistro de Usuario 3")
    print("Nombre completo: ")
    val nombre3 = readln()
    print("Edad: ")
    val edad3 = readln().toInt()
    print("Altura (en metros): ")
    val altura3 = readln().toDouble()
    print("Peso (en kilogramos): ")
    val peso3 = readln().toDouble()
    print("Email: ")
    val email3 = readln()
    print("Ciudad de residencia: ")
    val ciudad3 = readln()
    
    val imc3 = peso3 / (altura3 * altura3)
    
    println("\n=== INFORMACIÓN DE USUARIO 3 ===")
    println("Nombre: $nombre3")
    println("Edad: $edad3 años")
    println("Altura: $altura3 m")
    println("Peso: $peso3 kg")
    println("IMC: $imc3")
    println("Email: $email3")
    println("Ciudad: $ciudad3")
}
